Document: usermanage-client
Title: Debian usermanage-client Manual
Author: <insert document author here>
Abstract: This manual describes what usermanage-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/usermanage-client/usermanage-client.sgml.gz

Format: postscript
Files: /usr/share/doc/usermanage-client/usermanage-client.ps.gz

Format: text
Files: /usr/share/doc/usermanage-client/usermanage-client.text.gz

Format: HTML
Index: /usr/share/doc/usermanage-client/html/index.html
Files: /usr/share/doc/usermanage-client/html/*.html
