######################################################################
# Automatically generated by qmake (3.0) ?? 9? 28 11:33:42 2014
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = best
INCLUDEPATH += .

# Input
HEADERS += myPainter.h page.h
SOURCES += main.cpp myPainter.cpp page.cpp
